Importação de pacotes utilizados

In [21]:
import pandas as pd
import numpy as np

Carregamento do conjunto de dados

In [22]:
# Carregando o dataset IN C:\Users\scarlos\Documents\Análise_de_Dados\PROJETOS\EDA-PRODUTOS-AGRICOLAS\data\raw\agricultural_product_prices_1990_2020.csv
df = pd.read_csv(r'C:\\Users\scarlos\Documents\Análise_de_Dados\PROJETOS\EDA-PRODUTOS-AGRICOLAS\data\raw\agricultural_product_prices_1990_2020.csv')   

# Exibindo as primeiras linhas do dataset
df.head(10)

,Month,Coarse wool Price,Coarse wool price % Change,Copra Price,Copra price % Change,Cotton Price,Cotton price % Change,Fine wool Price,Fine wool price % Change,Hard log Price,...,Plywood Price,Plywood price % Change,Rubber Price,Rubber price % Change,Softlog Price,Softlog price % Change,Soft sawnwood Price,Soft sawnwood price % Change,Wood pulp Price,Wood pulp price % Change
0,Apr-90,482.34,-,236,-,1.83,-,"1,071.63",-,161.20,...,312.36,-,0.84,-,120.66,-,218.76,-,829.29,-
1,May-90,447.26,-7.27%,234,-0.85%,1.89,3.28%,"1,057.18",-1.35%,172.86,...,350.12,12.09%,0.85,1.19%,124.28,3.00%,213.00,-2.63%,842.51,1.59%
2,Jun-90,440.99,-1.40%,216,-7.69%,1.99,5.29%,898.24,-15.03%,181.67,...,373.94,6.80%,0.85,0.00%,129.45,4.16%,200.00,-6.10%,831.35,-1.32%
3,Jul-90,418.44,-5.11%,205,-5.09%,2.01,1.01%,895.83,-0.27%,187.96,...,378.48,1.21%,0.86,1.18%,124.23,-4.03%,210.05,5.03%,798.83,-3.91%
4,Aug-90,418.44,0.00%,198,-3.41%,1.79,-10.95%,951.22,6.18%,186.13,...,364.60,-3.67%,0.88,2.33%,129.70,4.40%,208.30,-0.83%,818.74,2.49%
5,Sep-90,412.18,-1.50%,196,-1.01%,1.79,0.00%,936.77,-1.52%,185.33,...,384.92,5.57%,0.90,2.27%,129.78,0.06%,199.59,-4.18%,811.62,-0.87%
6,Oct-90,394.64,-4.26%,198,1.02%,1.79,0.00%,901.85,-3.73%,189.76,...,409.31,6.34%,0.90,0.00%,121.31,-6.53%,206.98,3.70%,807.46,-0.51%
7,Nov-90,334.5,-15.24%,236,19.19%,1.82,1.68%,888.61,-1.47%,179.02,...,375.74,-8.20%,0.90,0.00%,130.50,7.58%,206.64,-0.16%,773.37,-4.22%
8,Dec-90,328.24,-1.87%,237,0.42%,1.85,1.65%,870.55,-2.03%,171.13,...,363.16,-3.35%,0.88,-2.22%,119.35,-8.54%,198.22,-4.07%,741.29,-4.15%
9,Jan-91,319.47,-2.67%,233,-1.69%,1.85,0.00%,887.41,1.94%,169.19,...,362.26,-0.25%,0.87,-1.14%,126.14,5.69%,186.94,-5.69%,721.85,-2.62%

Exploração do conjunto de dados

In [23]:
df.info()

#Verificando valores ausentes
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 361 entries, 0 to 360
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Month                         361 non-null    str
 1   Coarse wool Price             327 non-null    str
 2   Coarse wool price % Change    327 non-null    str
 3   Copra Price                   339 non-null    str
 4   Copra price % Change          339 non-null    str
 5   Cotton Price                  361 non-null    float64
 6   Cotton price % Change         361 non-null    str
 7   Fine wool Price               327 non-null    str
 8   Fine wool price % Change      327 non-null    str
 9   Hard log Price                361 non-null    float64
 10  Hard log price % Change       361 non-null    str
 11  Hard sawnwood Price           327 non-null    float64
 12  Hard sawnwood price % Change  327 non-null    str
 13  Hide Price                    327 non-null    float64
 14  Hide price % change           327 non-null    str
 15  Plywood Price                 361 non-null    float64
 16  Plywood price % Change        361 non-null    str
 17  Rubber Price                  361 non-null    float64
 18  Rubber price % Change         361 non-null    str
 19  Softlog Price                 327 non-null    float64
 20  Softlog price % Change        327 non-null    str
 21  Soft sawnwood Price           327 non-null    float64
 22  Soft sawnwood price % Change  327 non-null    str
 23  Wood pulp Price               360 non-null    float64
 24  Wood pulp price % Change      360 non-null    str
dtypes: float64(9), str(16)
memory usage: 70.6 KB

Month                            0
Coarse wool Price               34
Coarse wool price % Change      34
Copra Price                     22
Copra price % Change            22
Cotton Price                     0
Cotton price % Change            0
Fine wool Price                 34
Fine wool price % Change        34
Hard log Price                   0
Hard log price % Change          0
Hard sawnwood Price             34
Hard sawnwood price % Change    34
Hide Price                      34
Hide price % change             34
Plywood Price                    0
Plywood price % Change           0
Rubber Price                     0
Rubber price % Change            0
Softlog Price                   34
Softlog price % Change          34
Soft sawnwood Price             34
Soft sawnwood price % Change    34
Wood pulp Price                  1
Wood pulp price % Change         1
dtype: int64

Tratando dados ausentes, incorretos e inválidos

In [24]:
 # Remove sinais de percentual e vírgulas; transformar hífens isolados e strings vazias em NaN.
df = df.replace({r'%': '', r',': ''}, regex=True) # Remoção de porcentagem e vírgulas
df = df.replace(r'^\s*-\s*$', np.nan, regex=True) # Remoção de hífens isolados
df = df.replace(r'^\s*$', np.nan, regex=True)     # Remoção de strings vazias ou só espaços
df = df.replace('MAY90', np.nan)                  # Remoção de valores específicos que não são válidos

# Remove linhas com valores NaN
df = df.dropna()

# Verifica se tem valores ausentes no dataset
df.isnull().sum()

# Convertendo todas as colunas com valores inteiros para o tipo float; uma vez que se tratam de valores de preço e percentual.
lst = df.columns.tolist()[1:]  # Lista de todas as colunas, exceto a primeira (Month)
for col in lst:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df.dtypes

Month                               str
Coarse wool Price               float64
Coarse wool price % Change      float64
Copra Price                     float64
Copra price % Change            float64
Cotton Price                    float64
Cotton price % Change           float64
Fine wool Price                 float64
Fine wool price % Change        float64
Hard log Price                  float64
Hard log price % Change         float64
Hard sawnwood Price             float64
Hard sawnwood price % Change    float64
Hide Price                      float64
Hide price % change             float64
Plywood Price                   float64
Plywood price % Change          float64
Rubber Price                    float64
Rubber price % Change           float64
Softlog Price                   float64
Softlog price % Change          float64
Soft sawnwood Price             float64
Soft sawnwood price % Change    float64
Wood pulp Price                 float64
Wood pulp price % Change        float64
dtype: object

In [25]:
df.head(100)

,Month,Coarse wool Price,Coarse wool price % Change,Copra Price,Copra price % Change,Cotton Price,Cotton price % Change,Fine wool Price,Fine wool price % Change,Hard log Price,...,Plywood Price,Plywood price % Change,Rubber Price,Rubber price % Change,Softlog Price,Softlog price % Change,Soft sawnwood Price,Soft sawnwood price % Change,Wood pulp Price,Wood pulp price % Change
1,May-90,447.26,-7.27,234.0,-0.85,1.89,3.28,1057.18,-1.35,172.86,...,350.12,12.09,0.85,1.19,124.28,3.00,213.00,-2.63,842.51,1.59
2,Jun-90,440.99,-1.40,216.0,-7.69,1.99,5.29,898.24,-15.03,181.67,...,373.94,6.80,0.85,0.00,129.45,4.16,200.00,-6.10,831.35,-1.32
3,Jul-90,418.44,-5.11,205.0,-5.09,2.01,1.01,895.83,-0.27,187.96,...,378.48,1.21,0.86,1.18,124.23,-4.03,210.05,5.03,798.83,-3.91
4,Aug-90,418.44,0.00,198.0,-3.41,1.79,-10.95,951.22,6.18,186.13,...,364.60,-3.67,0.88,2.33,129.70,4.40,208.30,-0.83,818.74,2.49
5,Sep-90,412.18,-1.50,196.0,-1.01,1.79,0.00,936.77,-1.52,185.33,...,384.92,5.57,0.90,2.27,129.78,0.06,199.59,-4.18,811.62,-0.87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,Apr-98,379.81,-1.30,380.0,0.53,1.45,-3.97,627.82,0.30,166.49,...,372.14,-4.22,0.77,4.05,165.28,7.35,280.31,0.61,522.07,4.88
97,May-98,355.70,-6.35,420.0,10.53,1.42,-2.07,606.13,-3.45,146.68,...,362.69,-2.54,0.78,1.30,155.38,-5.99,297.55,6.15,540.01,3.44
98,Jun-98,348.24,-2.10,414.0,-1.43,1.52,7.04,595.30,-1.79,137.41,...,348.59,-3.89,0.70,-10.26,160.26,3.14,290.69,-2.31,559.52,3.61
99,Jul-98,308.83,-11.32,402.0,-2.90,1.54,1.32,583.14,-2.04,134.96,...,348.53,-0.02,0.70,0.00,141.85,-11.49,268.34,-7.69,533.86,-4.59
100,Aug-98,296.93,-3.85,403.0,0.25,1.50,-2.60,500.19,-14.22,136.94,...,335.25,-3.81,0.65,-7.14,173.47,22.29,269.07,0.27,507.91,-4.86